name: Analyze Repository Structure

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Analyze repository structure
        run: |
          echo "Current directory: $(pwd)"
          echo "Repository root contents:"
          ls -la
          echo "All files in the repository:"
          find . -type f
          echo "Git status:"
          git status
          echo "Git log (last 5 commits):"
          git log -n 5 --oneline

      - name: Check for scripts directory
        run: |
          if [ -d "scripts" ]; then
            echo "scripts directory found. Contents:"
            ls -la scripts
          else
            echo "scripts directory not found."
            echo "Directories in repository root:"
            find . -maxdepth 1 -type d
          fi

      - name: Search for monitor_repository.py
        run: |
          SCRIPT_PATH=$(find . -name monitor_repository.py -type f)
          if [ -n "$SCRIPT_PATH" ]; then
            echo "monitor_repository.py found at: $SCRIPT_PATH"
            echo "Contents of monitor_repository.py:"
            cat "$SCRIPT_PATH"
          else
            echo "monitor_repository.py not found in the repository."
          fi
