name: Monitor Repository

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Debug - Print working directory
        run: pwd

      - name: Debug - List directory contents
        run: ls -R

      - name: Navigate to correct directory and run script
        run: |
          cd $GITHUB_WORKSPACE
          python scripts/monitor_repository.py
        env:
          MULTION_API_KEY: ${{ secrets.MULTION_API_KEY }}

      - name: Create issue if problems detected
        if: failure()
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Repository monitoring detected issues
          content-filepath: ./monitoring_report.md
          token: ${{ secrets.GITHUB_TOKEN }}
