name: Monitor Repository

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: List contents of scripts directory
        run: |
          echo "Contents of scripts directory:"
          ls -la scripts/

      - name: Run monitoring script
        run: |
          if [ -f "scripts/monitor_repository.py" ]; then
            python scripts/monitor_repository.py
          else
            echo "Error: scripts/monitor_repository.py not found"
            echo "Files in scripts directory:"
            ls -la scripts/
            exit 1
          fi
        env:
          MULTION_API_KEY: ${{ secrets.MULTION_API_KEY }}

      - name: Check for monitoring report
        run: |
          if [ -f "monitoring_report.md" ]; then
            echo "Contents of monitoring_report.md:"
            cat monitoring_report.md
          else
            echo "Error: monitoring_report.md not found"
            exit 1
          fi

      - name: Create issue if problems detected
        if: failure()
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Repository monitoring detected issues
          content-filepath: ./monitoring_report.md
          token: ${{ secrets.GITHUB_TOKEN }}
