name: Monitor Repository

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests
      - name: Debug - Print working directory
        run: pwd
      - name: Debug - List directory contents
        run: ls -R
      - name: Monitor repository
        run: python monitor_repository.py
        working-directory: ${{ github.workspace }}/scripts
        env:
          MULTION_API_KEY: ${{ secrets.MULTION_API_KEY }}
      - name: Create issue if problems detected
        if: failure()
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Repository monitoring detected issues',
              body: 'The monitoring script detected potential issues. Please review the latest monitoring report.'
            })
