name: Monitor Repository

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Check MULTION_API_KEY
        run: |
          if [ -z "${{ secrets.MULTION_API_KEY }}" ]; then
            echo "MULTION_API_KEY is not set in the repository secrets."
            exit 1
          else
            echo "MULTION_API_KEY is set."
          fi

      - name: Run monitoring script
        run: |
          python scripts/monitor_repository.py
        env:
          MULTION_API_KEY: ${{ secrets.MULTION_API_KEY }}
        continue-on-error: true

      - name: Display script output
        if: always()
        run: |
          echo "Script Output:"
          cat monitoring_report.md || echo "monitoring_report.md not found"
          echo "Error Output:"
          cat error.log || echo "error.log not found"

      - name: Create issue if problems detected
        if: failure()
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Repository monitoring detected issues
          content-filepath: ./monitoring_report.md
          token: ${{ secrets.GITHUB_TOKEN }}
